server:
  port: 8888
spring:
  security:
    user:
      name: xsj284
      password: 123456
  # 配置数据源
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/learn
      username: root
      password: 123456
      driver: com.mysql.cj.jdbc.Driver
# swagger配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html