/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        App: typeof import('./App.vue')['default']
        AppLayout: typeof import('./layouts/AppLayout.vue')['default']
        ElAside: typeof import('element-plus/es')['ElAside']
        ElContainer: typeof import('element-plus/es')['ElContainer']
        ElHeader: typeof import('element-plus/es')['ElHeader']
        ElMain: typeof import('element-plus/es')['ElMain']
        ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
        HelloWorld: typeof import('./components/HelloWorld.vue')['default']
        HomeView: typeof import('./views/HomeView.vue')['default']
        LinkButton: typeof import('./components/Header/LinkButton.vue')['default']
        LoginLayout: typeof import('./layouts/LoginLayout.vue')['default']
        LoginView: typeof import('./views/LoginView.vue')['default']
        MyLogo: typeof import('./components/MyLogo.vue')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
    }
}
